# Generated by Django 5.2.7 on 2025-10-17 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('codice', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True, verbose_name='Codice Sala')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tema', models.CharField(max_length=50, verbose_name='Tema')),
                ('mq', models.IntegerField(verbose_name='Metri Quadri')),
            ],
            options={
                'verbose_name_plural': 'Sale',
                'ordering': ['codice'],
            },
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('nProg', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Numero Progressivo')),
                ('cliente', models.CharField(max_length=4, verbose_name='Codice Cliente')),
                ('data', models.DateField(verbose_name='Data')),
                ('ora', models.TimeField(verbose_name='Ora')),
                ('posto', models.IntegerField(verbose_name='Posto')),
                ('abbonamento', models.CharField(max_length=100, verbose_name='Codice Abbonamento')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.sala', verbose_name='Codice Sala')),
            ],
            options={
                'verbose_name_plural': 'Prenotazioni',
                'ordering': ['sala'],
            },
        ),
        migrations.CreateModel(
            name='FasciaOraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('ora', models.TimeField(verbose_name='Ora')),
                ('durata', models.IntegerField(verbose_name='Durata (in minuti)')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name_plural': 'Fasce Orarie',
                'ordering': ['data', 'ora'],
            },
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('ora', models.TimeField(verbose_name='Ora')),
                ('nProg', models.IntegerField(verbose_name='Numero Progressivo')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.sala', verbose_name='Codice Sala')),
            ],
            options={
                'verbose_name_plural': 'Posti',
                'ordering': ['sala'],
                'unique_together': {('sala', 'data', 'ora', 'nProg')},
            },
        ),
    ]
