# Generated by Django 5.2.7 on 2025-11-12 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienti', '0001_initial'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='clienti.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.sala', verbose_name='Sala'),
        ),
    ]
