# Generated by Django 5.2.7 on 2025-10-17 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codice', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='Codice Cliente')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cognome', models.CharField(max_length=50, verbose_name='Cognome')),
                ('cf', models.CharField(max_length=16, verbose_name='Codice Fiscale')),
                ('dataNas', models.DateField(verbose_name='Data di nascita')),
                ('indirizzo', models.CharField(max_length=128, verbose_name='Indirizzo')),
                ('tel', models.CharField(max_length=24, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=64, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='SubAbbonamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenotazione', models.CharField(max_length=10, verbose_name='Prenotazione')),
                ('abbonamento', models.CharField(max_length=10, verbose_name='Abbonamento')),
            ],
            options={
                'verbose_name': 'SubAbbonamento',
                'verbose_name_plural': 'SubAbbonamenti',
            },
        ),
        migrations.CreateModel(
            name='Abbonamento',
            fields=[
                ('nAbb', models.CharField(default='null', max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='Numero Abbonamento')),
                ('inizio', models.DateField(verbose_name='Data di inizio')),
                ('fine', models.DateField(verbose_name='Data di fine')),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prezzo abbonamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abbonamenti', to='clienti.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Abbonamento',
                'verbose_name_plural': 'Abbonamenti',
                'ordering': ['-fine'],
            },
        ),
    ]
